[Stats]
aiStyle=19
;Spear style AI
friendly=True
height=100
hide=True
;Was not entirely sure what this was used for
melee=True
;Spears do melee damage
scale=1.0
timeLeft=3600
type=-1
width=100
pretendType=47
;one of the spear projectile AI's in the stock game
useTime=12
tileCollide=false
penetrate=6
;This causes wall penetration for a spear allowing it to hit any mobs through walls