[Stats]
width=38
height=18
type=-1
useAnimation=100
useTime=100
maxStack=1
scale=1
defense=20
bodySlot=-2
hasArms=True
toolTip=10% increased critical strike chance, 5% increased melee damage
toolTip2=21% increased melee and movement speed
;set as -2 for custom armor pieces
rare=3
setName=Dragon
;for setBonus items
value=100000
className=Item
[Recipe]
Amount=1
needWater=False
Tiles=Mythril Anvil
Items=1 Hallowed Plate Mail,1 Cobalt Breastplate,1 Mythril Chainmail,1 Adamantite Breastplate,15 Soul of Might,20 Soul of Blight