[Stats]
width=38
height=18
type=-1
useAnimation=100
useTime=100
maxStack=1
scale=1
defense=15
bodySlot=-2
hasArms=True
toolTip=5% increased magical damage,10% reduced mana use,10% increased magical critical strike chance
toolTip2=23% reduced mana usage
;set as -2 for custom armor pieces
rare=3
setName=Spectral
;for setBonus items
value=100000
className=Item
[Recipe]
Amount=1
needWater=False
Tiles=Mythril Anvil
Items=1 Hallowed Plate Mail,1 Cobalt Breastplate,1 Mythril Chainmail,1 Adamantite Breastplate,10 Soul of Fright,20 Soul of Blight