[Stats]
damage=50
height=48
knockBack=6.5
maxStack=1
melee=True
noMelee=True
noUseGraphic=True
rare=3
scale=1.1
shootSpeed=7
projectile=Tonbogiri
;the spear's projectile
type=-1
prefixType=368
useAnimation=25
useSound=1
useStyle=5
useTime=15
value=27000
width=48
[Recipe]
Items=1 Gungnir,15 Soul of Blight,15 Adamantite Bar
Tiles=Mythril Anvil
Amount=1
needWater=False

